#pragma once
#include <bts/blockchain/outputs.hpp>

namespace bts { namespace lotto {
   

enum claim_type_enum
{
   /** basic claim by single address */
   claim_secret			= 30,
   claim_ticket         = 31
   
};


struct claim_ticket_input
{
    static const claim_type_enum type;
};

struct claim_ticket_output
{
    static const claim_type_enum type;
    
    claim_ticket_output():lucky_number(0), odds(1){}

    /**
     *  This is the number chosen by the user or at 
     *  random, ie: their lotto ticket number.
     */
    uint64_t                   lucky_number;

    /**
     *  Who owns the ticket and thus can claim the jackpot
     */
    bts::blockchain::address   owner;

    /** The probability of winning... increasing the odds will 
     * cause the amount won to grow by Jackpot * odds, but the
     * probability of winning decreases by 2*odds.
     */
    uint16_t                   odds; 
};

struct claim_secret_input
{
	static const claim_type_enum type;
};

struct claim_secret_output
{
	static const claim_type_enum type;

	claim_secret_output() :secret(fc::sha256()), revealed_secret(fc::sha256()), delegate_id(0){}

	fc::sha256					secret;  // HASH( S[n] ) where n is the index in the array of secrets generated by this delegate
	fc::sha256					revealed_secret; //  S[n-1]
	uint32_t					delegate_id;
};

}} //bts::lotto

FC_REFLECT_ENUM(bts::lotto::claim_type_enum, (claim_ticket)(claim_secret));
FC_REFLECT(bts::lotto::claim_ticket_input, BOOST_PP_SEQ_NIL);
FC_REFLECT(bts::lotto::claim_ticket_output, (owner)(odds));
FC_REFLECT(bts::lotto::claim_secret_input, BOOST_PP_SEQ_NIL);
FC_REFLECT(bts::lotto::claim_secret_output, (secret)(revealed_secret)(delegate_id))
