#pragma once

#define BTS_LOTTO_RED_SET_COUNT (35)
#define BTS_LOTTO_RED_COMBINATION_COUNT (5)
#define BTS_LOTTO_BLUE_SET_COUNT (12)
#define BTS_LOTTO_BLUE_COMBINATION_COUNT (2)

#define BTS_LOTTO_RED_COMBINATION_COUNT (324632)	// C(35, 5)
#define BTS_LOTTO_BLUE_COMBINATION_COUNT (66)		// C(12, 2)
#define BTS_LOTTO_TOTAL_COMBINATION_COUNT (324632 * 66)	// BTS_LOTTO_RED_COMBINATION_COUNT * BTS_LOTTO_BLUE_COMBINATION_COUNT
